version: '3.7'

services:
  # Serviço para o script de verificação do site
  site-checker:
    build: .
    container_name: site-checker
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  # Prometheus para coletar métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  # Grafana para visualização
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

networks:
  default:
    driver: bridge
